
patch_size: 16



Aggregator:
  _target_: models.Aggregator
  visual_encoder_2d:
    _target_: models.VisualEncoder2D
    model_name: dinov3-vitb16
    keep_attn: True    # It should be 'False' when training, False by default. Set for DINOv3
  visual_encoder_3d:
    _target_: models.VisualEncoder3D
    model_name: MinkUnet
    feats_channels: 6  # Indicating how many dimensions of feature, e.g. 6 for a point contains features [r, g, b, n_x, n_y, n_z] 
    out_dim: 256

