patch_size: 16
voxel_size: 0.02

# defaults:
#   - aggregator@Aggregator.aggregator: ${aggregation_fn}  # ✅ 动态注入到 Aggregator.aggregator 字段

aggregation_fn: cross_attn  
Aggregator:
  _target_: models.Aggregator
  aggregation_fn: ${aggregation_fn} 
  # 这里写死就可以了，动态注入有点麻烦，更换方式的话多改动一些即可
  aggregator:
    _target_: models.CrossAttention
    d_model: 256
    num_heads: 8
    dropout: 0.1

  visual_encoder_2d:
    _target_: models.VisualEncoder2D
    model_name: dinov3-vitb16
    keep_attn: True

  visual_encoder_3d:
    _target_: models.VisualEncoder3D
    model_name: MinkUnet
    coords_dim: 3
    feats_dim: 6
    last_dim: 256
    arch_3d: MinkUNet34C

  mlp:
    _target_: models.MLP
    input_dim: 512
    hidden_dim: 256
    output_dim: 256
    layer_order: "pre"
    dropout: 0.1
